### PR TITLE
Improve Makefile

### PR DESCRIPTION
**Pull request by ema-pe**
Hi, I saw your project on Reddit, and I would want to improve it. The world isn't big, because I discovered that you are a fellow student in the same university (but different year).
Anyway, I found that your Makefile should be improved, the main feature is that now it can automatically detect `.c` and `.h` source files; the other changes are small improvements (like follow the GNU Makefile conventions).

### CODE REVIEW

**Comment by ema-pe** [comment]
Feel free to ask any question! I have a serious advice: choose a LICENSE! Github repositories without a LICENSE are not open source software; so please choose a license. I suggest the MIT License.

**Comment by MarcoLucidi01** [comment]
Thank you, it looks really nice now, I guess I'm going to use it as "starting point" for future projects!

I have only one problem with the `install` target: `$(CP)` variable doesn't work on my system (Debian 9.1):
```bash
$ sudo make install
tasks /usr/local/bin
make: tasks: Command not found
Makefile:38: recipe for target 'install' failed
make: *** [install] Error 127
$ 
```
It should be an "implicit variable" of make, right? `$(RM)` works though.

Yes, I definitely have to look into licenses and such...it's a task in my todo list xD

**Comment by ema-pe** [comment]
Hi, `$(CP)` seems not supported by GNU Make, but it is curious because `$(RM)` it is. The [manual](https://www.gnu.org/software/make/manual/make.html#Utilities-in-Makefiles) doesn't say other... I don't know, so I fixed using `cp` directly.

**Comment by MarcoLucidi01** [comment]
Ok, I squashed `Fix install target in Makefile` and `Improve Makefile` together and then merged the branch into `master`, but GitHub didn't close the pull request automatically (because of my rebase I guess), I think I have to do it manually.
I hope I did the right thing, let me know if I screw up! (Was my first time merging from a pull request).

**Comment by ema-pe** [comment]
It is strange, because it seems that GitHub didn't recognize that you've merged commits. Maybe because you didn't accept the pull request via GitHub.

**Pull request closed without merging**
